print("Ejercicio 1")
numeros=("1,2,3,4,5")
print(numeros[1])
print(len(numeros))
print(numeros.index(4))
print(numeros.count(2))
mitupla=("hola mundo",12,3.14)
print(mitupla)
tuplaanimada=((1,2),3)
print("primer valor de la tuplaanimada: ",tuplaanimada)